# Generated by Django 4.2.7 on 2023-11-30 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('text', models.TextField(max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
